version: "3.7"

services:
  games_download:
    build: .
    container_name: games_download_service
    restart: always
    ports:
      - 5001:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/app/
