version: "3.7"

services:
  carbone:
    container_name: carbone
    # image: ochom/carbone:latest
    build: .
    restart: on-failure:1
    ports:
      - 5001:8080
    volumes:
      - .:/app
      - /app/node_modules
