version: "3.7"

services:
  games_download:
    build: https://${GITHUB_TOKEN}@github.com/solami-limited/download-games.git#main
    container_name: games_download_service
    restart: always
    ports:
      - 5001:3000
    volumes:
      - ./templates:/usr/src/app/templates
    environment:
      - PORT=3000
    env_file:
      - .env
